---
title: "Module 9 Assignment"
author: "GEOG-3440"
output: html_document
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(echo = TRUE)
```

Be sure to **read assigned chapters and articles** and carefully walk through all of the **Module Guide** before starting on this task.

*Avoid using packages or solutions beyond the content covered in class or the guide.*

**Submit** your responses in a single, organized html file written in *R Markdown.*

<br />


## **Module Tasks**

Complete the following tasks related to the content of this week. Be sure that each answer is given in an organized, coded solution. All plots should at minimum contain useful axes labels and title.

<br />

*An important aspect of spatial analysis is the relationship of nearby features and the ability to extend sparse measurements to a more spatially complete understanding. In this module, you will extend measurement information across larger spatial domains through remote sensing and spatial interpolation.*

<br />

## **Remote Sensing**

Remote sensing provides spatially continuous information, with limitations in spatial, temporal, and spectral resolution.

Download and unzip the *landsat_wasatch.zip* file. This folder contains several cropped level 2 surface reflectance landsat scenes for the Wasatch during the Winter-Spring of 2024. You will estimate snow cover extent and how it changes based on the [Normalized Difference Snow Index](https://www.usgs.gov/landsat-missions/normalized-difference-snow-index) (NDSI) starting with a standard threshold of values greater than or equal to 0.4 (*as snow*). You may adjust the value slightly if it appears to capture snow better, but keep a consistent threshold for all scenes.

1. (3 pts) Create a single map plot that combines snow cover extent over all available scenes to visualize how snow cover changed from March-June in 2024. Values should indicated *months* of snow cover per pixel. Use a gradient of blue colors.

2. (2 pts) Create a scatterplot or barplot showing the total snow covered area (in km^2) by date. Also, provide an estimate of the monthly change in snow cover over the spring season.

(*optional*) *Combine your snow cover extents with terrain characteristics (e.g., slope, aspect) to see how topography influences snow melt.*

<br />

## **Spatial Interpolation**

Spatial interpolation is another method to expand observations. Continue working with the **"UTSNTL_2021_2023_SWE_Joined.csv"** SNOTEL SWE dataset, filter this to Water Year 2022. You will interpolate SWE values across the state. Also, read in and dissolve the **"UT_HUC8.shp"** polygon to obtain a mask (border) for the state.

3. (4 pts) Interpolate SWE (values) across the state of Utah using: 1) nearest neighbor, 2) inverse distance weighting, and 3) detrended-retrended IDW using elevation from the `geodata` package. Produce three final plots (side-by-side), masking out elevations below the minimum SNOTEL site for the state. *See tips below for additional help*

*Tips:*

- Use the code provided in the module guide to perform all interpolation
- Note that there are additional options for IDW, for example, try adjusting the inverse distance power with the argument `set = list(idp = .5)` or `idp = 3`.
- For 3rd map, create a linear model using the swe *values* as a function of station *elevation* (in ft)
- For 3rd map, retrend the data using a DEM of the state downloaded from `geodata` (see module 8) - clip using the extent UT (dissolved HUC polygons)
- Consider the units of the DEM and the elevation provided in the SNOTEL dataframe
- Consider best use of color to show your results (e.g. `hcl.colors(25, "Blues")`)
- For better visualization, plot the state of Utah with an Earth-tone color first (e.g. col=`"navajowhite3"`), then add the interpolated snow cover layer (masked to SNOTEL elevations) over the top.

```r
# use course geodata elevation for retrending
library(geodata)
dem=elevation_30s("USA", res=2.5, path=tempdir())
# crop this to the extent of Utah
```

<br />

4. (1 pt) Describe how you might combine remote sensing and interpolation methods to monitor the snowpack and water storage (volume) in the Wasatch. List a few considerations to keep in mind while creating a spatially accurate estimate of snow water storage.

<br />

#### Submitting

Upload a single, organized **html file** written in **R Markdown** showing **questions, code solutions, and responses**. Be sure to support your responses with code and result outputs.

*Please reach out if you have any questions or concerns!*

<br />
<br />


