---
title: "Module 5 Assignment"
author: "GEOG-3440"
output: html_document
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(echo = TRUE)
```

Be sure to **read assigned chapters and articles** and carefully walk through all of the **Module Guide** before starting on this task.

*Avoid using packages or solutions beyond the content covered in class or the guide.*

**Submit** your responses in a single, organized html file written in *R Mardown.*

<br />


## **Module Tasks**

Complete the following tasks related to the content of this week. Be sure that each answer is given in an organized, coded solution. All plots should at minimum contain useful axes labels and title.

**Consider** our discussion on significant figures for your responses below.

<br />

##### **Snow statistics**

Revisit the Timpanogos Divide SNOTEL data, `snotel820_timp.csv`, previously used to assess the relationship between variables. If needed, convert dates to the proper format and recalculate **density** using the equation listed in Module 04.

1. Consider which variables might be most closely related with snow depth (`depth`). Use the `cor` function to explore the relationship between snow depth and swe, density, and t_max. Using the reported correlation, describe how snow depth is related to these other variables.

Create a new DataFrame that is a subset of the original and **only includes dates after January, 10th**, which are dates during the height of the storm (*you can see this by plotting snow depth over time as a line*). 

Recall that the amount (depth) of snow that falls during a storm mainly depends on *density*, which is related to the *air temperature*. As such, we should see a relationship between air temperature and density.

2. Fit a linear model (`lm`) of daily snow *density* as a function of the *average temperature* (`t_ave`) using the storm *subset* dataset. Report the $R^{2}$ and p-value and describe the statistical strength of the relationship and direction (i.e. positive or negative). Provide a scatterplot with the linear model shown. (*Tip, you can retreive the multiple* $R^{2}$ *from the model fit with* `summary(fit)$r.squared` *and the pvalue with* `summary(fit)$coefficients[2,4]`, *the model can be added to a plot with* `abline()`)

3. Still using the storm subset, fit another linear model for the change (`diff`) in daily snow depth (*depth*) as a function of the change (`diff`) in snow *density*. Report the $R^{2}$ and p-value and describe how changes in density affect snow depth


<br />    

#### **Cleaning data**

Read in the `messy_state_elev.csv` data. First, you will need to clean up this data frame so it is in a more usable format. This data was scraped from this [USGS website](https://www.usgs.gov/educational-resources/highest-and-lowest-elevations) and has been slightly modified to make one step easier.

Note that there are two columns for elevation, the first relates to the highest elevation, and the second is the lowest elevation.

4. (*2 pts*) Show steps to clean and reformat each column in the dataset based on the list below. To show this, use the `summary()` and `head()` to summarize your final cleaned dataset. At minimum, do the following:

  - Use existing column names (*e.g. first word*) as input to reassign new column names to something more concise (*i.e. use string manipulation rather than manually changing all names*). *Tip, one way is to use* `gsub` *with* `pattern = "\\..*$"` *to remove everything after the first literal* `.`*, then the* `make.unique` *function to handle columns that might end with the same name* ( `strsplit`*, or other pattern matching can also work*)
  - In the elevation columns, remove special characters `{ }` with the digits in them. Then commas `,` in both elevation columns (the bracket numbers come from superscript references when the data was scraped). *Tip, unfortunately we cannot remove all* `"[[:punct:]]"` *with* `gsub` *as it would leave us with elevations higher than Everest. Instead, it might be best to use* `gsub` *twice, first removing the brackets with digits and a second time removing all commas. For pattern matching, the* `\\` *is used for literal matches, which is needed because brackets are also used for grouping items in pattern matching. You can catch all digits and brackets in your pattern.*
  - Next, replace all instances of "Sea level" in the low elevation column with the value of 0. *Tip, use* `gsub` *again and use one statement to account for the fact that sometimes Level is capitalized, and sometimes not* (*e.g.* `[Aa]pples` *will search for any variation of apples or Apples, or the* `lower` *function can be helpful*).
  - Finally, convert both elevation columns into numeric type data (*make sure you correctly completed steps above to avoid* `NA` *values*)
  - Create a new column for *elevation_range* based on the difference in the high and low elevations.

5. Is the elevation range of states in the US normally distributed? Provide evidence. Also, list the total number and names of all *States* that have an elevation range greater than two miles (*one mile = 5,280 ft*).


<br />

#### **Combining and analyzing data**

Read in the `us-pop.csv` data. This dataset was obtained from the US Census Bureau's [website](https://www.census.gov/data/tables/time-series/dec/popchange-data-text.html) and contains decennial population information over the past five decades for each state or territory in the US.

The us-pop data will need to be cleaned up a bit as well. The `skip =` argument can be useful when reading in a csv file to skip unnecessary lines at the top of the document. You may need to open the file to see how many lines (*number*) to use in the skip argument. *See documentation* `?read.csv` *for more help.* Also, rename the column names so that they are easier to work with.

6. Use similar techniques as above to convert all population columns to numeric. This will require you to remove all *commas* before to converting to numeric. *Tip: while you could do this column-by-column, it is a good opportunity to combine iteration with* `sapply` *and* `gsub`. *For example, you can reassign entire columns in the data with something like* `pop[,2:ncol(pop)] <- sapply(pop[,2:ncol(pop)], FUN = gsub, ... )` *and specifying the pattern, and replacement. Then you will need to use* `sapply` *again on these columns with* `as.numeric`.

Create a new columns that contains the percent change in population for each state from 2010 to 2020, which shows the increase in population (as a percentage) from 2010-2020. As a reminder, a percent change can be calculated with:

$$Percent Change = \frac{end - start}{start} * 100$$

7. List the **top 6 states** *(and values)* with the greatest increase in population from 2010 to 2020 (*show only the state name and population increase in 2020*).

Use the `merge` function with the USGS elevation dataset (above) and the us-pop data. To join dataframes together, you will need to find a common variable name in each dataset for the merge (*note, you can specify different column names to merge for each dataset, see* `by.` *in* `?merge`).

You have a loose *hypothesis*, you think that the elevation range of a state partly determined the change in population from 2010-2020 (*note, this is different from hypothesis testing in statistics*).

8. Run a linear model of the percent change in population from 2010-2020 as a function of the elevation range in your merged dataset. Report the p-value and $R^2$. Do your results support your hypothesis?

Through research, you have determined that several US states have experienced singular events that may have offset their population over the past several decades. You have sufficient justification to exclude these states from your analysis. Use the list below to filter these states from your dataset:

```r
exclude_states <- c("Alaska", "California", "Delaware", "District of Columbia", "Florida", "Hawaii", "New Mexico","North Dakota", "Puerto Rico", "West Virginia", "Wyoming")
```

**Tip:** You can use indexing and boolean logic with the `%in%` function to help match and filter state names in this dataset. For example, `1:5 %in% c(2,5)` returns `# [1] FALSE  TRUE FALSE FALSE  TRUE`. Recall that `!` negates logic (is the inverse).

Create a *subset* of your merged data that excludes the states above. 

9. Show your code to subset the data frame to exclude the above states. Then, fit another linear model to assess the relationship again between the percent change in population from 2010-2020 as a function of the elevation range with this subset. Create a scatterplot that shows the linear fit and report the p-value and $R^2$. What can you say about your hypothesis?


<br />

#### Submitting

Upload a single, organized **html file** written in **R Markdown**, clearly showing **questions, code solutions, and responses**. Be sure to support your responses with code and result outputs.

*Please reach out if you have any questions or concerns!*

<br />

