---
title: "Module 4 Assignment"
author: "GEOG-3440"
output: html_document
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(echo = TRUE)
```

Be sure to **read assigned chapters and articles** and carefully walk through all of the **Module Guide** before starting on this task.

*Avoid using packages or solutions beyond the content covered in class or the guide.*

**Submit** your responses in a single, organized html file written in *RMardown.*

<br />


## **Module Tasks**

Complete the following tasks related to the content of this week. Be sure that each answer is given in an organized, coded solution. All plots should at minimum contain useful axes labels and title.

<br />

##### **School Days**

Using the start *(Jan, 6)* and end *(April, 22)* dates of the spring 2025 semester, create a datetime object and answer questions 1-3:

1. Find the total number of days in the semester, and total number of school days.

2. Extract all dates that fall on a Saturday and count the total number of Saturdays in the semester. *hint: look up the* `weekdays` *function.*

3. Round up and assume that we meet from 1-4PM (3 hrs) each day for this class. Use the dates of the semester and these details to calculate the number of hours you will spend in this class this semester. *(no need to consider holidays or missed classes)*

<br />

##### **Probability**

Use a *for loop* to create a new dataset of dice rolls to start thinking about probabilities. 

4. Take the sum of 10 rolls for a six-sided dice using the `sample` function with `replace=TRUE`. Show histograms of the 10 roll sums for 10 iterations and 10,000 iterations (i.e. create a vector of 10 then 10K values of the result at each iteration). What is a good estimate of the average of the 10 roll sum?


<br />

##### **Snow data**

Read in csv file provided in canvas. This file contains daily snow and meteorological data for 30 days from December, 24, 2023 to January, 22 2024 collected at the snow telemetry (Snotel) station at the Timpanogos Divide.

For context, snow water equivalent is the amount of water in the snowpack or a volume of snow and is calculated by multiplying the snow density ($\rho$) by depth (*d*):

$$SWE = \rho * d$$
a brief explanation of other variables are also listed:

- date - Date string corresponding to local time (convert dates column to a date format)
- swe - Snow water equivalent at the start of the day (inches)
- swe_med - Historical median swe at the start of the day for 1991-2020 (inches)
- depth - Snow depth (inches)
- prec_accum - Total accumulated (cumulative) water for current water year (Oct 1st) (inches)
- prec_med - historical median prec_accum for 1991-2020 (inches)
- t_max - Air temperature maximum of the day ($^{o}F$) 
- t_min - Air temperature minimum of the day ($^{o}F$) 
- t_ave - Air temperature average of the day ($^{o}F$) 

Respond to the following questions:

5. Use the equation above to estimate the density of the snowpack for each day (add this as a new column), and list the average and standard deviation of the following: snow density (*in percent*), snow depth, and average temperature for the time period. Add this information into a single `print` or `cat` statement.

6. How do density and snow depth vary over time? Create a single plot showing both snow depth and density as a function of time. *Note you can use the `lines()` or `points()` functions to add more to an existing scatter/line plot.* What day seems to mark the transition from clear to stormy weather?

7. Is there a relationship between snow water equivalent and precipitation accumulation? Describe any other relationships you observe between variables in this dataset. *For now simple visualizations work to explore relationships.*

8. Create a new column called swe_perc showing the snow water equivalent as a percent of the median historical swe value for each day. Plot these values and describe how the swe values track with the median historical values.

9. How much total snow (*depth*) was gained or lost from the start to end of time period? How much snow water equivalent was gained or lost? 

10. Calculate the daily incremental change in both snow depth and SWE over the 30 day period. Sum both the gains and losses from each and compare these values to the values in the previous question. Hypothesize as to what might account for the differences between the change in snow depth vs the change in SWE?



<br />

#### Submitting

Upload a single, organized **html file** written in **R Markdown** showing **questions, code solutions, and responses**. Be sure to support your responses with code and result outputs.

*Please reach out if you have any questions or concerns!*

<br />

